version: 2.1 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/gls # directory where steps will run
    docker: # run the steps with Docker
      - image: cimg/openjdk:8.0-node

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Avoid hosts unknown for github
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - run:
          name: Clone and Build RSKj
          command: |
                  GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                  git clone -b PAPYRUS-2.1.0 git@github.com:rsksmart/rskj.git ~/rsksmart/rskj
                  cd ~/rsksmart/rskj/
                  ./configure.sh
                  ./gradlew clean build -x test

      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-yarn2
      - run:
          name: yarn-install
          command: yarn

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-yarn2
          paths:
            - ./node_modules

      - run:
          name: Start RskJ & Run Tests
          command: |
                    java -Dminer.client.autoMine=true -Drsk.conf.file=~/gls/rsknode/node.conf -Dminer.minGasPrice=1 -cp ~/rsksmart/rskj/rskj-core/build/libs/rskj-core-2.1.0-PAPYRUS-all.jar co.rsk.Start --regtest nohup &               
                    until nc -z 127.0.0.1 4444
                    do
                      echo "Waiting for RskJ..."
                      sleep 1
                    done
                    yarn test-rsk
      - store_artifacts:
          path: ~/gls/logs